var teamData = [
	{
	"teamName":"Arizona Diamondbacks",
	"logo": "https://upload.wikimedia.org/wikipedia/en/8/89/Arizona_Diamondbacks_logo.svg",
	
	"textColor": "#000000",
	"color1": "#E3D4AD",
	"color2": "#A71930",
	"color3": "#000000",
	"color4": "teal",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "white",

	"league": "National League",
	"details": "Established 1998 <br> Ballpark: Chase Field",
	},
	{
	"teamName":"Atlanta Braves",
	"logo": "https://upload.wikimedia.org/wikipedia/en/f/f2/Atlanta_Braves.svg",
	"textColor": "#FFFFFF",
	"color1": "#CE1141",
	"color2": "#13274F",
	"color3": "#EAAA00",
	"color4": "#fcf6dc",
	"color5": "white",

	"text1": "black",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "National League",
	"details": "Established 1871 <br> Ballpark: SunTrust Park",
	},
	{
	"teamName":"Baltimore Orioles",
	"logo": "https://upload.wikimedia.org/wikipedia/en/7/75/Baltimore_Orioles_cap.svg",
	"textColor": "#FFFFFF",
	"color1": "#DF4601",
	"color2": "#ff8649",
	"color3": "#000000",
	"color4": "#B5B6B8",
	"color5": "white",

	"text1": "white",
	"text2": "black",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1901 <br> Ballpark: Camden Yards",
	},
	{
	"teamName":"Boston Red Sox",
	"logo": "https://upload.wikimedia.org/wikipedia/en/6/6d/RedSoxPrimary_HangingSocks.svg",
	"textColor": "#FFFFFF",
	"color1": "#BD3039",
	"color2": "#0C2340",
	"color3": "#154976",
	"color4": "#d5d9db",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1901 <br> Ballpark: Fenway Park",
	},
	{
	"teamName":"Chicago White Sox",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Chicago_White_Sox.svg",
	"textColor": "#FFFFFF",
	"color1": "#27251F",
	"color2": "#FFFFFF",
	"color3": "#C4CED4",
	"color4": "black",
	"color5": "#c4c2c2",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "white",
	"text5": "white",

	"league": "American League",
	"details": "Established 1888 <br> Ballpark: Guaranteed Rate Field",
	},
	{
	"teamName":"Chicago Cubs",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/8/80/Chicago_Cubs_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#CC3433",
	"color2": "#0E3386",
	"color3": "#49a2ce",
	"color4": "#f0f4f8",
	"color5": "white",

	"text1": "black",
	"text2": "white",
	"text3": "black",
	"text4": "white",
	"text5": "black",

	"league": "National League",
	"details": "Established 1876 <br> Ballpark: Wrigley Field",
	},
	{
	"teamName":"Cincinnati Reds",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/0/01/Cincinnati_Reds_Logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#C6011F",
	"color2": "#FFFFFF",
	"color3": "#000000",
	"color4": "#c4c2c2",
	"color5": "#a00a0b",

	"text1": "white",
	"text2": "black",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "National League",
	"details": "Established 1881 <br> Ballpark: Great American Ball Park",
	},
	{
	"teamName":"Cleveland Indians",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Cleveland_Indians_primary_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#0C2340",
	"color2": "#E31937",
	"color3": "#000000",
	"color4": "#c4c2c2",
	"color5": "white",

	"text1": "white",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "white",

	"league": "American League",
	"details": "Established 1894 <br> Ballpark: Progressive Field",
	},
	{
	"teamName":"Colorado Rockies",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/3/31/Colorado_Rockies_logo.svg",
	"textColor": "#000000",
	"color1": "#8B8D8B",
	"color2": "#33006F",
	"color3": "#000000",
	"color4": "#C4CED4",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "National League",
	"details": "Established 1991 <br> Ballpark: Coors Field",
	},
	{
	"teamName":"Detroit Tigers",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Detroit_Tigers_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#F64616",
	"color2": "#062340",
	"color3": "#000000",
	"color4": "#c4c2c2",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1894 <br> Ballpark: Comerica Park",
	},
	{
	"teamName":"Houston Astros",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Houston-Astros-Logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#002D62",
	"color2": "#EB6E1F",
	"color3": "#f4871e",
	"color4": "#c4c2c2",
	"color5": "white",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1962 <br> Ballpark: Minute Maid Park",
	},
	{
	"teamName":"Kansas City Royals",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/8/88/Kansas_City_Royals_Insignia.svg",
	"textColor": "#FFFFFF",
	"color1": "#004687",
	"color2": "#BD9B60",
	"color3": "#7bb1dd",
	"color4": "#c4c2c2",
	"color5": "white",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "white",
	"text5": "white",

	"league": "American League",
	"details": "Established 1969 <br> Ballpark: Kauffman Stadium",
	},
	{
	"teamName":"Los Angeles Angels",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Los_Angeles_Angels_of_Anaheim.svg",
	"textColor": "#FFFFFF",
	"color1": "#003263",
	"color2": "#BA0021",
	"color3": "#862633",
	"color4": "#C4CED4",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "white",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1961 <br> Ballpark: Angel Stadium",
	},
	{
	"teamName":"Los Angeles Dodgers",
	"logo": "https://upload.wikimedia.org/wikipedia/en/6/69/Los_Angeles_Dodgers_logo.svg",
	"textColor": "#000000",
	"color1": "white",
	"color2": "#223b75",
	"color3": "#E71D35",
	"color4": "#A5ACAF",
	"color5": "#6cace4",

	"text1": "white",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "National League",
	"details": "Established 1883 <br> Ballpark: Dodger Park",
	},
	{
	"teamName":"Miami Marlins",
	"logo": "https://upload.wikimedia.org/wikipedia/en/0/0d/Marlins_cap_insignia.svg",
	"textColor": "#000000",
	"color1": "#EF3340",
	"color2": "#00A3E0",
	"color3": "#41748D",
	"color4": "#000000",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "white",
	"text4": "white",
	"text5": "white",

	"league": "National League",
	"details": "Established 1993 <br> Ballpark: Marlins Park",
	},
	{
	"teamName":"Milwaukee Brewers",
	"logo": "https://upload.wikimedia.org/wikipedia/en/1/11/Milwaukee_Brewers_Logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#0A2351",
	"color2": "#ffce07",
	"color3": "#bf975c",
	"color4": "#212c64",
	"color5": "white",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "white",
	"text5": "white",

	"league": "National League",
	"details": "Established 1969 <br> Ballpark: Miller Park",
	},
	{
	"teamName":"Minnesota Twins",
	"logo": "https://upload.wikimedia.org/wikipedia/en/7/71/Minnesota_Twins_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#002B5C",
	"color2": "#D31145",
	"color3": "#a5acaf",
	"color4": "#6bacde",
	"color5": "#cfab7a",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1894 <br> Ballpark: Target Field",
	},
	{
	"teamName":"New York Yankees",
	"logo": "https://upload.wikimedia.org/wikipedia/en/2/25/NewYorkYankees_PrimaryLogo.svg",
	"textColor": "#000000",
	"color1": "#C0C0C0",
	"color2": "#003087",
	"color3": "#0C2340",
	"color4": "white",
	"color5": "#001C43",

	"text1": "white",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "white",

	"league": "American League",
	"details": "Established 1901 <br> Ballpark: Yankee Stadium(II)",
	},
	{
	"teamName":"New York Mets",
	"logo": "https://upload.wikimedia.org/wikipedia/en/7/7b/New_York_Mets.svg",
	"textColor": "#FFFFFF",
	"color1": "#002D72",
	"color2": "#FF5910",
	"color3": "#0d4c8f",
	"color4": "#f68121",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "white",
	"text4": "white",
	"text5": "white",

	"league": "National League",
	"details": "Established 1962 <br> Ballpark: Citi Field",
	},
	{
	"teamName":"Oakland Athletics",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Oakland_A%27s_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#003831",
	"color2": "#EFB21E",
	"color3": "#008440",
	"color4": "#A2AAAD",
	"color5": "white",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "white",

	"league": "American League",
	"details": "Established 1901 <br> Ballpark: Oakland Coliseum",
	},
	{
	"teamName":"Philadelphia Phillies",
	"logo": "https://upload.wikimedia.org/wikipedia/en/4/47/New_Phillies_logo.png",
	"textColor": "#FFFFFF",
	"color1": "#E81828",
	"color2": "#002D72",
	"color3": "#284898",
	"color4": "#fff9ec",
	"color5": "white",

	"text1": "white",
	"text2": "white",
	"text3": "black",
	"text4": "white",
	"text5": "white",

	"league": "National League",
	"details": "Established 1883 <br> Ballpark: Citizens Bank Park",
	},
	{
	"teamName":"Pittsburgh Pirates",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/8/81/Pittsburgh_Pirates_logo_2014.svg",
	"textColor": "#FFFFFF",
	"color1": "#27251F",
	"color2": "#FDB827",
	"color3": "#fdcf31",
	"color4": "#c4c2c2",
	"color5": "white",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "black",
	"league": "National League",
	"details": "Established 1882 <br> Ballpark: PNC Park",
	},
	{
	"teamName":"San Diego Padres",
	"logo": "https://upload.wikimedia.org/wikipedia/commons/a/a4/SDPadres_logo.svg",
	"textColor": "#000000",
	"color1": "#A2AAAD",
	"color2": "#002D62",
	"color3": "#4e2200",
	"color4": "#FFC72C",
	"color5": "#473729",

	"text1": "white",
	"text2": "black",
	"text3": "black",
	"text4": "white",
	"text5": "white",

	"league": "National League",
	"details": "Established 1969 <br> Ballpark: Petco Park",
	},
	{
	"teamName":"San Fransisco Giants",
	"logo": "https://upload.wikimedia.org/wikipedia/en/5/58/San_Francisco_Giants_Logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#27251F",
	"color2": "#FD5A1E",
	"color3": "#EFD19F",
	"color4": "#AE8F6F",
	"color5": "white",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "white",
	"text5": "white",

	"league": "National League",
	"details": "Established 1883 <br> Ballpark: Oracle Park",
	},
	{
	"teamName":"Seattle Mariners",
	"logo": "https://upload.wikimedia.org/wikipedia/en/b/b0/Seattle_Mariners_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#0C2C56",
	"color2": "#005C5C",
	"color3": "#C4CED4",
	"color4": "white",
	"color5": "#dc3058",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1977 <br> Ballpark: T-Mobile Park",
	},
	{
	"teamName":"St. Louis Cardinals",
	"logo": "https://upload.wikimedia.org/wikipedia/en/9/9d/St._Louis_Cardinals_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#C41E3A",
	"color2": "#0C2340",
	"color3": "#FEDB00",
	"color4": "#71a6ce",
	"color5": "white",

	"text1": "black",
	"text2": "white",
	"text3": "black",
	"text4": "black",
	"text5": "black",

	"league": "National League",
	"details": "Established 1882 <br> Ballpark: Busch Stadium",
	},
	{
	"teamName":"Tampa Bay Rays",
	"logo": "https://upload.wikimedia.org/wikipedia/en/c/c6/Tampa_Bay_Rays.svg",
	"textColor": "#FFFFFF",
	"color1": "#092C5C",
	"color2": "#8FBCE6",
	"color3": "#F5D130",
	"color4": "#FFFFFF",
	"color5": "silver",

	"text1": "black",
	"text2": "black",
	"text3": "white",
	"text4": "white",
	"text5": "white",

	"league": "American League",
	"details": "Established 1998 <br> Ballpark: Tropicana Field",
	},
	{
	"teamName":"Texas Rangers",
	"logo": "https://upload.wikimedia.org/wikipedia/en/4/41/Texas_Rangers.svg",
	"textColor": "#FFFFFF",
	"color1": "#003278",
	"color2": "#C0111F",
	"color3": "#002d72",
	"color4": "silver",
	"color5": "white",

	"text1": "white",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1961 <br> Ballpark: Globe Life Park",
	},
	{
	"teamName":"Toronto Blue Jays",
	"logo": "https://upload.wikimedia.org/wikipedia/en/b/ba/Toronto_Blue_Jays_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#134A8E",
	"color2": "#E8291C",
	"color3": "#1D2D5C",
	"color4": "WHITE",
	"color5": "#0476BF",

	"text1": "white",
	"text2": "black",
	"text3": "white",
	"text4": "black",
	"text5": "black",

	"league": "American League",
	"details": "Established 1977 <br> Ballpark: Rogers Centre",
	},
	{
	"teamName":"Washington Nationals",
	"logo": "https://upload.wikimedia.org/wikipedia/en/a/a3/Washington_Nationals_logo.svg",
	"textColor": "#FFFFFF",
	"color1": "#AB0003",
	"color2": "#14225A",
	"color3": "#FFFFFF",
	"color4": "#a61e36",
	"color5": "#212c64",

	"text1": "black",
	"text2": "white",
	"text3": "black",
	"text4": "white",
	"text5": "white",

	"league": "National League",
	"details": "Established 1969 <br> Ballpark: Nationals Park",
	},
]
























