var teamDemo = [
	{
	"teamName":"Arizona Diamondbacks",
	// "label":"MLB Players EXAMPLE",
	"white": 65,
	"black": 2.5,
	"latino": 27.5,
	"asian": 2.5,
	"other": 0,
	},
	{
	"teamName":"Atlanta Braves",
	// "label":"MLB Players EXAMPLE",
	"white": 72.5,
	"black": 2.5,
	"latino": 17.5,
	"asian": 0,
	"other": 7.5,
	},

	{
	"teamName":"Baltimore Orioles",
	// "label":"MLB Players EXAMPLE",
	"white": 67.5,
	"black": 12.5,
	"latino": 20,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Boston Red Sox",
	// "label":"MLB Players EXAMPLE",
	"white": 62.5,
	"black": 7.5,
	"latino": 22.5,
	"asian": 2.5,
	"other": 2.5,
	},
	{
	"teamName":"Chicago Cubs",
	// "label":"MLB Players EXAMPLE",
	"white": 68.2,
	"black": 7.6,
	"latino": 19.4,
	"asian": 4.8,
	"other": 0,
	},
	{
	"teamName":"Chicago White Sox",
	// "label":"MLB Players EXAMPLE",
	"white": 47.5,
	"black": 5,
	"latino": 42.5,
	"asian": 0,
	"other": 5,
	},
	{
	"teamName":"Cincinnati Reds",
	// "label":"MLB Players EXAMPLE",
	"white": 65.8,
	"black": 7.3,
	"latino": 25,
	"asian": 2.4,
	"other": 0,
	},
	{
	"teamName":"Cleveland Indians",
	// "label":"MLB Players EXAMPLE",
	"white": 62.5,
	"black": 7.5,
	"latino": 25,
	"asian": 5,
	"other": 0,
	},
	{
	"teamName":"Colorado Rockies",
	// "label":"MLB Players EXAMPLE",
	"white": 67.5,
	"black": 2.5,
	"latino": 27.5,
	"asian": 2.5,
	"other": 0,
	},
	{
	"teamName":"Detroit Tigers",
	// "label":"MLB Players EXAMPLE",
	"white": 55,
	"black": 10,
	"latino": 35,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Houston Astros",
	// "label":"MLB Players EXAMPLE",
	"white": 55,
	"black": 10,
	"latino": 32.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Kansas City Royals",
	// "label":"MLB Players EXAMPLE",
	"white": 72.5,
	"black": 7.5,
	"latino": 22.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Los Angeles Angels",
	// "label":"MLB Players EXAMPLE",
	"white": 57.5,
	"black": 5,
	"latino": 32.5,
	"asian": 2.5,
	"other": 2.5,
	},
	{
	"teamName":"Los Angeles Dodgers",
	// "label":"MLB Players EXAMPLE",
	"white": 70,
	"black": 15,
	"latino": 5,
	"asian": 5,
	"other": 2.5,
	},
	{
	"teamName":"Miami Marlins",
	// "label":"MLB Players EXAMPLE",
	"white": 45,
	"black": 5,
	"latino": 42.5,
	"asian": 7.5,
	"other": 0,
	},
	{
	"teamName":"Milwaukee Brewers",
	// "label":"MLB Players EXAMPLE",
	"white": 62.5,
	"black": 10,
	"latino": 27.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Minnesota Twins",
	// "label":"MLB Players EXAMPLE",
	"white": 50,
	"black": 7.5,
	"latino": 40,
	"asian": 0,
	"other": 2.5,
	},
	{
	"teamName":"New York Yankees",
	// "label":"MLB Players EXAMPLE",
	"white": 50,
	"black": 10,
	"latino": 30,
	"asian": 5,
	"other": 5,
	},
	{
	"teamName":"New York Mets",
	// "label":"MLB Players EXAMPLE",
	"white": 67.5,
	"black": 5,
	"latino": 27.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Oakland Athletics",
	// "label":"MLB Players EXAMPLE",
	"white": 67.5,
	"black": 7.5,
	"latino": 22.5,
	"asian": 0,
	"other": 2.5,
	},
	{
	"teamName":"Philadelphia Phillies",
	// "label":"MLB Players EXAMPLE",
	"white": 42.5,
	"black": 10,
	"latino": 47.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Pittsburgh Pirates",
	// "label":"MLB Players EXAMPLE",
	"white": 52.5,
	"black": 10,
	"latino": 32.5,
	"asian": 2.5,
	"other": 2.5,
	},
	{
	"teamName":"San Diego Padres",
	// "label":"MLB Players EXAMPLE",
	"white": 62.5,
	"black": 0,
	"latino": 37.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"San Fransisco Giants",
	// "label":"MLB Players EXAMPLE",
	"white": 72.5,
	"black": 0,
	"latino": 27.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Seattle Mariners",
	// "label":"MLB Players EXAMPLE",
	"white": 60,
	"black": 12.5,
	"latino": 22.5,
	"asian": 2.5,
	"other": 2.5,
	},
	{
	"teamName":"St. Louis Cardinals",
	// "label":"MLB Players EXAMPLE",
	"white": 62.5,
	"black": 7.5,
	"latino": 27.5,
	"asian": 0,
	"other": 2.5,
	},
	{
	"teamName":"Tampa Bay Rays",
	// "label":"MLB Players EXAMPLE",
	"white": 65,
	"black": 2.5,
	"latino": 32.5,
	"asian": 0,
	"other": 0,
	},
	{
	"teamName":"Texas Rangers",
	// "label":"MLB Players EXAMPLE",
	"white": 47.5,
	"black": 10,
	"latino": 35,
	"asian": 5,
	"other": 2.5,
	},
	{
	"teamName":"Toronto Blue Jays",
	// "label":"MLB Players EXAMPLE",
	"white": 60,
	"black": 7.5,
	"latino": 25,
	"asian": 0,
	"other": 2.5,
	},
	{
	"teamName":"Washington Nationals",
	// "label":"MLB Players EXAMPLE",
	"white": 60,
	"black": 7.5,
	"latino": 27.5,
	"asian": 2.5,
	"other": 2.5,
	},
]












